### ISSUE TITLE
Client may not be able to fulfill OnAgentPackageAvailable

### ISSUE THREAD

**Issue by kart** [open-telemetry/opamp-go#44]
Currently, the `OpAMPClient` calls `OnAgentPackageAvailable` on receiving `protobufs.AgentPackageAvailable` message. The signature of this callback is:

```
// OnAgentPackageAvailable is called when the server has an agent package available
// for the agent.
// syncer can be used to initiate syncing the package from the server.
OnAgentPackageAvailable(addons *protobufs.AgentPackageAvailable, syncer AgentPackageSyncer) error
```

Unless the client is told ahead of time who the `AgentPackageSyncer` is, the client cannot successfully fulfill this callback as it doesn't have enough context to construct a valid `syncer`. More importantly, I think the client doesn't need to. Instead, I suggest we ignore the syncer altogether on the callback and just provide the details of the available agent package along with a context and let the callback handler deal with the actual syncing part which is most likely to be the supervisor which has enough knowledge about the agent and how to sync the packages.

The same is true for `OnAddonsAvailable` too.

**Comment by tigrannajaryan** [comment]
>Unless the client is told ahead of time who the AgentPackageSyncer is, the client cannot successfully fulfill this callback as it doesn't have enough context to construct a valid syncer. 

1. The AgentPackageSyncer knows how to communicate with the OpAMP Server.
2. The AgentPackageSyncer.Sync() method is given an AgentPackageStateProvider instance which provides means to fetch the current local state and mutate the local state (update the package file content).

Is this not a sufficient context? What other context is necessary to perform the the syncing process?

>Instead, I suggest we ignore the syncer altogether on the callback and just provide the details of the available agent package along with a context and let the callback handler deal with the actual syncing part which is most likely to be the supervisor which has enough knowledge about the agent and how to sync the packages.

This would require the callback handler to be able to perform downloading of package/addon files, send progress reports, etc. Generally this would the implementation of OnAgentPackageAvailable to drive the entire process and for that to become possible we need to also expose additional methods on OpAMPClient so that progress reports can be sent.

I am not sure this makes things simpler, but perhaps it does. Can you submit a draft PR to show what you think it can look like? I assume you want to eliminate AgentPackageSyncer/AgentPackageStateProvider/AddonSyncer/AddonStateProvider interfaces, right?

**Comment by tigrannajaryan** [comment]
Closing since package syncing has changed and this no longer seems relevant.
